on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploying to Digitalocean droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        private_key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
              cd /var/www/html/global-test-repo
              git pull
